name: Build Linux Android Toolchain

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - swift-android-5.4-branch
  pull_request:
    branches:
      - swift-android-5.4-branch

jobs:

  build-icu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo ./github-actions/010_install_dependencies.sh
    - name: Install NDK
      run: ./github-actions/020_install_ndk_16b.sh
    - name: Define build folders
      run: ./vagrant/provision/030_define_build_folders.sh
    - name: Cache ICU
      id: cache-icu
      uses: actions/cache@v2
      with:
        path: |
          /home/runner/libiconv-libicu-android/arm64-v8a
          /home/runner/libiconv-libicu-android/armeabi-v7a
          /home/runner/libiconv-libicu-android/x86_64
          /home/runner/libiconv-libicu-android/x86
        key: ${{ runner.os }}-ee2cf7f
    - name: Build ICU
      if: steps.cache-icu.outputs.cache-hit != 'true'
      run: ./build/Linux/010-build-icu.sh
    - uses: actions/upload-artifact@v2
      with:
        name: icu-arm64-v8a
        path: |
          /home/runner/libiconv-libicu-android/arm64-v8a
          !/home/runner/libiconv-libicu-android/arm64-v8a/icu
          !/home/runner/libiconv-libicu-android/arm64-v8a/android_support
          /home/runner/libiconv-libicu-android/arm64-v8a/icu/**/*.h
    - uses: actions/upload-artifact@v2
      with:
        name: icu-armeabi-v7a
        path: |
          /home/runner/libiconv-libicu-android/armeabi-v7a
          !/home/runner/libiconv-libicu-android/armeabi-v7a/icu
          !/home/runner/libiconv-libicu-android/armeabi-v7a/android_support
          /home/runner/libiconv-libicu-android/armeabi-v7a/icu/**/*.h
    - uses: actions/upload-artifact@v2
      with:
        name: icu-x86_64
        path: |
          /home/runner/libiconv-libicu-android/x86_64
          !/home/runner/libiconv-libicu-android/x86_64/icu
          !/home/runner/libiconv-libicu-android/x86_64/android_support
          /home/runner/libiconv-libicu-android/x86_64/icu/**/*.h
    - uses: actions/upload-artifact@v2
      with:
        name: icu-x86
        path: |
          /home/runner/libiconv-libicu-android/x86
          !/home/runner/libiconv-libicu-android/x86/icu
          !/home/runner/libiconv-libicu-android/x86/android_support
          /home/runner/libiconv-libicu-android/x86/icu/**/*.h


  build-swift-arm-64:
    needs: build-icu
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo ./github-actions/010_install_dependencies.sh
    - name: Install NDK
      run: ./github-actions/020_install_ndk_21e.sh
    - name: Define build folders
      run: ./vagrant/provision/030_define_build_folders.sh
    - uses: actions/download-artifact@v2
      with:
        name: icu-arm64-v8a
        path: /home/runner/libiconv-libicu-android/arm64-v8a
    - name: Clone Swift
      run: ./build/Linux/020-clone-swift.sh
    - name: Cache Swift Arm64
      id: cache-swift-arm-64
      uses: actions/cache@v2
      with:
        path: /home/runner/out/swift-android-5.4
        key: ${{ runner.os }}-arm64-e1e3863
    - name: Build Swift
      if: steps.cache-swift-arm-64.outputs.cache-hit != 'true'
      run: ./build/Linux/031-build-swift-arm64.sh
    - uses: actions/upload-artifact@v2
      with:
        name: swift-nightly-install-arm64-v8a
        path: /home/runner/out/swift-android-5.4
